name: Generate Snake Animation

on:
  schedule:
    # Atualiza todo dia às 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: samanthinhamilgrau
          outputs: dist/github-contribution-grid-snake.svg

      - name: Subir arquivo gerado
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Atualizando snake.svg"
          add: "dist/github-contribution-grid-snake.svg"

      - name: Publicar no branch output
        run: |
          mkdir -p output
          mv dist/github-contribution-grid-snake.svg output/
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/github-contribution-grid-snake.svg
          git commit -m "Atualizando snake animation"
          git push origin HEAD:output --force
